// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4xDsmSpgT5rjlZIN2SA4gN08fIh4C_bs',
    appId: '1:517199330577:android:abcdef1234567890', // Need Android app config
    messagingSenderId: '517199330577',
    projectId: 'flutter-pos-ai',
    storageBucket: 'flutter-pos-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4xDsmSpgT5rjlZIN2SA4gN08fIh4C_bs',
    appId: '1:517199330577:ios:e0e68c2d0e0ebb595ba0b0',
    messagingSenderId: '517199330577',
    projectId: 'flutter-pos-ai',
    storageBucket: 'flutter-pos-ai.firebasestorage.app',
    iosBundleId: 'com.ai.pos',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTzoypCq1TsQeZpfKrSTQamQ7C6hht-Dc',
    appId: '1:207877947347:web:15e5080683611feadd3926',
    messagingSenderId: '207877947347',
    projectId: 'pos-ai-odoo',
    authDomain: 'pos-ai-odoo.firebaseapp.com',
    storageBucket: 'pos-ai-odoo.firebasestorage.app',
  );

}